AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
