---
inherit_mode:
  merge:
    - Exclude

Workit/ActionArgs:
  Description: |
    Check for controller action must be using `action_args`.
  Enabled: pending
  Include:
    - 'controllers/**/*'
  ControllerMethods:
    - index
    - show
    - create
    - update
    - cancel
    - destroy

Workit/ComitteeAssertSchemaConfirm:
  Description: |
    Check for not pass expected response status code to check it against the corresponding schema explicitly.
  Enabled: false

Workit/NoopRescue:
  Description: 'Check for suppress or ignore checked exception.'
  Enabled: false

Workit/RestrictOnSend:
  Description: |
    Check for `RESTRICT_ON_SEND` is defined if `on_send` or `after_send` are defined.
  Enabled: pending
