---
inherit_mode:
  merge:
    - Exclude

Workit/ActionArgs:
  Description: |
    Check for controller action must be using `action_args`.
  Enabled: pending
  VersionAdded: '0.2'
  Include:
    - 'controllers/**/*'
  ControllerMethods:
    - index
    - show
    - create
    - update
    - cancel
    - destroy

Workit/RestrictOnSend:
  Description: |
    Check for `RESTRICT_ON_SEND` is defined if `on_send` or `after_send` are defined.
  Enabled: pending
  VersionAdded: '0.1'
