name: Markdownlint
on:
  - pull_request
jobs:
  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Markdownlint
        uses: avto-dev/markdown-lint@master
        with:
          args: "./**/*.md"
